Error Communication Color Changed
intermine/cross-intermine-search-tool pull request #12
Opened 2018-12-26 18:19 UTC by flaredragon

Fixes #8 
Screenshot of Change of Color - 
![screenshot from 2018-12-26 23-45-27](https://user-images.githubusercontent.com/29121452/50453739-cce02080-0968-11e9-9635-7d2a5c26f5b9.png)

2018-12-27 16:09 UTC, amand1996 commented
Looks good to me. Requested review from @yochannah

2018-12-28 09:24 UTC, yochannah requested changes
hey @flaredragon! Thank for making a start on this. I have a couple of comments below before we can merge. It might also be nice to consider a light grey with dark text rather than the light red we have. 

Let me know if anything isn't clear!

2018-12-28 09:24 UTC, yochannah commented on src/App.vue
> +     background-color: #FF9494 !important;
This is a great start! It's better to avoid `!important` if possible, though - see https://uxengineer.com/css-specificity-avoid-important-css/

2018-12-28 09:24 UTC, yochannah commented on src/App.vue
> +  #error {
Maybe make this a class instead? It seems possible we might want more than one element that looks like this.

2018-12-28 09:32 UTC, yochannah commented on src/App.vue
> +     background-color: #FF9494 !important;
Quick note - sometimes it can be a pain figuring out the correct selector to use to override a rule. If you need help, let us know!

2018-12-28 17:16 UTC, flaredragon commented
Hi @yochannah @amand1996 Thanks for your inputs.I made some changes but seem to have combined the two issues I was working on so I am closing this Pull Request and opening a new one.

2018-12-28 17:16 UTC, closed without merging

2018-12-28 17:19 UTC, yochannah commented
Sounds good, and thanks!! 👍